insert into tournament values(800031414,"Canyon Creek Country Club Indoor Doubles Classic (Non-Sanctioned)","Canyon Creek Country Club","Richardson","");
insert into tournament values(800039114,"Tournament Credit JAN 2014 (Adults / Seniors)","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(800031714,"ZAT Warm-Up Tournament at Canyon Creek (Non-Sanctioned)","Canyon Creek Country Club","Richardson","");
insert into tournament values(800008014,"Bay Area Racquet Club Adult & Junior Open (Jr, Ad)","Bay Area Racquet Club","Houston","");
insert into tournament values(800031614,"2014 USTA Texas ZAT & CMZ Test","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(800044014,"2014 USTA Texas ZAT & CMZ Test #2","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(800025214,"2014 USTA Texas ZAT & CMZ Test #3","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(800043414,"2014 USTA Texas ZAT & CMZ Test #4","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(810005714,"Giammalva RC Future Stars (Jr)","Giammalva Racquet Club","Spring","");
insert into tournament values(800010014,"South Texas CTA ZAT","South Texas CTA","McAllen","");
insert into tournament values(809656914,"Tyler Winter ZAT","Faulkner Tennis Center","Tyler","davidkemp.dk@gmail.com");
insert into tournament values(800001714,"WALNUT CREEK CHAMPIONSHIP MAJOR ZONE (CMZ)","Walnut Creek Country Club","Mansfield","");
insert into tournament values(800031114,"BERRY CREEK WINTER ADULT OPEN 2014 (Ad)","Berry Creek Racquet Club","Georgetown","tjwright50@austin.rr.com");
insert into tournament values(800015614,"LCCC WTA New Year Indoor Doubles Tournament (Ad)","Las Colinas Country Club","Irving","rmtennis@yahoo.com");
insert into tournament values(809674314,"MCCTA January Tournament (Jr, Ad, Sr, SS)","Missouri City Cta","Missouri City","mccta123@me.com");
insert into tournament values(800034414,"2014 USTA Texas SCMZ Compass Test","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(800005014,"Austin Super Championship Doubles Excellence (SCMZ 12_18)","Capital Area Tennis Association","Austin","rick_gabel@yahoo.com");
insert into tournament values(809719814,"BCS New Year Champ Major Zone 2014 (CMZ)","Brazos Valley Tennis Association","Bryan","");
insert into tournament values(809604614,"DPTA ChampSuper Challenger Canyon Creek (Jr)","Canyon Creek Country Club","Richardson","");
insert into tournament values(809645314,"KATY ZAT 1","Willow Fork Country Club","Katy","");
insert into tournament values(809702614,"LAKES ZAT","Lakes Tennis Academy","Frisco","Lonestarpictures@aol.com");
insert into tournament values(809655814,"Subway_BBI Tennis Central Texas ZAT","BBI Tennis Group","Belton","herbertsnert@cpu-net.net");
insert into tournament values(809663114,"GTC Junior Freeze (Jr)","Georgetown Tennis Center","Georgetown","mikemhenry@aol.com");
insert into tournament values(809654014,"Hardcourt Championships (Jr, Ad, Sr, SS)","Tennis Professional International","Houston","mrsaliciathomas@gmail.com");
insert into tournament values(800005414,"Polar Brrrr Nothing but Doubles Adult Major Zone (Ad)","Capital Area Tennis Association","Austin","tjwright50@austin.rr.com");
insert into tournament values(800100114,"2014 USTA Texas SCMZ FIC Test","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(800020414,"Aggieland Junior Open (Jr)","Aggieland Tennis","College Station","bgldbrg33@hotmail.com");
insert into tournament values(800028914,"DPTA JUNIOR CIRCUIT No. 5 - Fretz Tennis (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800031914,"SAN ANTONIO SUPER CHAMPIONSHIP LEVEL 3 (SCMZ 16_18)","San Antonio Tennis Assn.","San Antonio","RPerme2002@yahoo.com");
insert into tournament values(809682414,"Waco Super Championship Level 3 (SCMZ 12_14)","Waco Regional Tennis and Fitness","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(800051813,"10th Annual Bent Tree Country Club Late Nite Indoor Doubles Classic (Non-Sanctioned)","Bent Tree Country Club","Dallas","");
insert into tournament values(809679314,"ATA Winter Open (formerly Spenco Open) (Jr)","Austin Tennis Academy","Austin","mikemhenry@aol.com");
insert into tournament values(800008714,"METROPLEX WINTER CLASSIC ADULTS and JUNIORS Non-Qualified,Champs & Super Champs (Jr, Ad, Sr, SS)","Metroplex Tennis Association Inc.","Dallas","");
insert into tournament values(809725514,"WTA Frostbite Open (Jr, Ad, Sr, SS)","Waco Tennis Association","Waco","");
insert into tournament values(800031814,"2014 Michael Malone Junior Classic (Non-Sanctioned)","Westwood Country Club","Austin","");
insert into tournament values(800038414,"Bay Oaks Winter Jr Open (Non-Sanctioned)","Bay Oaks Country Club","Houston","");
insert into tournament values(800834614,"College Station Rotary Club Charity Classic","Brazos Valley Tennis Association","Bryan","");
insert into tournament values(800016214,"GII Junior Open (Jr)","Gloger Interests, Inc","Houston","");
insert into tournament values(800026914,"GII Junior Open (Jr)","Gloger Interests, Inc","Houston","");
insert into tournament values(800022914,"New Year's Woodlands Adult Open (Ad)","The Woodlands High School","The Woodlands","bgldbrg33@hotmail.com");
insert into tournament values(800019114,"SOUTHLAKE FUTURE STARS #1","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(800030914,"MABRY ADULT Open and SENIOR and SUPER SENIOR MAJOR ZONE (Ad, Sr, SS)","San Antonio Tennis Assn.","San Antonio","dnk57@sbcglobal.net");
insert into tournament values(800032714,"BROOKHAVEN MTA INDOOR DOUBLES CHAMPIONSHIPS (Ad)","Brookhaven Country Club","Dallas","rmtennis@yahoo.com");
insert into tournament values(809657514,"Austin Tennis Academy Glimmer of Hope ZAT","Austin Tennis Academy","Austin","RPerme2002@yahoo.com");
insert into tournament values(809603614,"DPTA ChampSuper Challenger Lakes (Jr)","Dallas Professional Tennis Association","Dallas","lonestarpictures@aol.com");
insert into tournament values(800032514,"DTA Winter ZAT","Dallas Tennis Assoc.","Addison","susan.wert10s@gmail.com");
insert into tournament values(800032614,"HTA ZAT # 1","Houston Tennis Association","Houston","");
insert into tournament values(800032214,"MIDLAND February ZAT","Tennis Association Of Midland","Midland","fsrainh2o@sbcglobal.net");
insert into tournament values(800032314,"RACQUET PRO DEER PARK CHAMPIONSHIP MAJOR ZONE (CMZ)","Deer Park I.S.D./Deer Park Tennis","Deer Park","patnjohn65@aol.com");
insert into tournament values(800021614,"River Crest Spring Mid-Cities Jr. Tournament (Non-Sanctioned)","River Crest Country Club","Fort Worth","");
insert into tournament values(800003414,"South Texas CTA Feb ZAT","South Texas CTA","McAllen","");
insert into tournament values(809612714,"Tournament Credit FEB 2014 (Adults/Seniors)","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(800012114,"Berry Creek Jr Winter Open (Jr)","Berry Creek Racquet Club","Georgetown","");
insert into tournament values(800032814,"CATA Gran Prix Polo Club Jr Open (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(809703414,"Horseshoe Bay Resort Red Clay Adult Open (Ad)","Horseshoe Bay Resort","Horseshoe Bay","");
insert into tournament values(800006814,"MCCTA February Tournament (Jr, Ad, Sr, SS)","Missouri City Cta","Houston","miguelm2353@gmail.com");
insert into tournament values(800015914,"Oasis Winter Adult and Junior Open (Jr, Ad)","Oasis Beach and Tennis Club","Rockwall","spulley12@hotmail.com");
insert into tournament values(800020814,"10's Participation Credit Tournament - Wichita Falls","Wichita Falls Tennis Association","Wichita Falls","");
insert into tournament values(800032914,"CORPUS CHRISTI SUPERS EXCELLENCE (SCMZ 12_16)","Corpus Christi Tennis Association","Corpus Christi","gerry@cctennisshop.com");
insert into tournament values(809706014,"Dallas Super Champ Excellence (SCMZ 14_18)","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(800029114,"DPTA JUNIOR CIRCUIT No. 6 - CANYON CREEK CC (Non-Sanctioned)","Canyon Creek Country Club","Richardson","");
insert into tournament values(800035114,"Las Colinas Spring Mid Cites (Non-Sanctioned)","Las Colinas Country Club","Irving","");
insert into tournament values(809620914,"WFTA FEB JR CHAMP MAJOR ZONE (CMZ)","Wichita Falls Tennis Association","Wichita Falls","weekspark@aol.com");
insert into tournament values(800023014,"Woodlands Tennis  Junior Open (Jr)","The Woodlands Tennis","Spring","bgldbrg33@hotmail.com");
insert into tournament values(800041914,"Bay Oaks / Lexus Adult & Junior Valentine's Doubles/Singles Classic (Non-Sanctioned)","Bay Oaks Country Club","Houston","");
insert into tournament values(800014614,"Lakecliff  Junior Spring Open (Jr)","Lakecliff Raquet Club","Spicewood","");
insert into tournament values(809663214,"Sunshine Cup (Jr, Ad, Sr, SS)","Tennis Professional International","Houston","mrsaliciathomas@gmail.com");
insert into tournament values(800021114,"Aggieland Junior Open (Jr)","Aggieland Tennis","College Station","bgldbrg33@hotmail.com");
insert into tournament values(800039514,"All Saints Mid-Cities (Non-Sanctioned)","All Saints Episcopal School","Fort Worth","");
insert into tournament values(800032014,"Brazos Valley Tennis Association Gran Prix 6-14 (Non-Sanctioned)","Brazos Valley Tennis Association","Bryan","");
insert into tournament values(800001914,"Closed USTA Regional Tournament","South Plains Tennis Association","Lubbock","susan.wert10s@gmail.com");
insert into tournament values(809627114,"DPTA Champ Super Challenger Fair Oaks Tournament (Jr)","Dallas Professional Tennis Association","Dallas","lonestarpictures@aol.com");
insert into tournament values(800021914,"Hill Country Future Stars (Jr)","H.E.B. Municipal Tennis Center","Kerrville","");
insert into tournament values(800036814,"National 18s Section Tournament","Canyon Creek Cc","Richardson","");
insert into tournament values(800001314,"USTA Closed Regional Tournament- February (Region 2)","Deer Park I.S.D./Deer Park Tennis","Deer Park","patnjohn65@aol.com");
insert into tournament values(800002814,"USTA Closed Regional Tournament- February (Region 2)","Giammalva Racquet Club","Spring","ginny_james@hotmail.com");
insert into tournament values(800000414,"USTA National Selection Tournament- February","St. Stephen's Episcopal School","Austin","director@austintennis.org");
insert into tournament values(800000814,"USTA National Selection Tournament- February","San Antonio Tennis Association","San Antonio","dnk57@sbcglobal.net");
insert into tournament values(800038614,"USTA National Selection Tournament- February","Arlington Tennis Center (Parks & Recreation)","Arlington","");
insert into tournament values(800002414,"USTA Regional Tournament Segment- February (Waco)","Waco Regional Tennis and Fitness","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(800038314,"Walnut Creek Jack Frost Open (Non-Sanctioned)","Walnut Creek Country Club","Mansfield","");
insert into tournament values(800024714,"AESA Jr Open at Polo Tennis Club (Jr)","Polo Tennis & Fitness Club","Austin","");
insert into tournament values(800014914,"Lakecliff  Open (Ad)","Lakecliff Raquet Club","Spicewood","");
insert into tournament values(809600114,"Lakes Tennis Academy Adult  Levels (Ad)","Lakes Tennis Academy","Frisco","Lonestarpictures@aol.com");
insert into tournament values(800006014,"SAPTA-H.E.B. Adult Major Zone (San Antonio) (Ad)","San Antonio Professional Tennis Association","San Antonio","redoaks@gvtc.com");
insert into tournament values(800007714,"Bay Area Racquet Club/ Racquet Pro Junior Open (Jr)","Bay Area Racquet Club","Houston","");
insert into tournament values(800021014,"Berry Creek Future Stars (Jr)","Berry Creek Racquet Club","Georgetown","");
insert into tournament values(800019914,"Giammalva RC Future Stars (Jr)","Giammalva Racquet Club","Spring","");
insert into tournament values(800035414,"Ridglea Country Club Spring Mid-Cities Jr Tournament (Non-Sanctioned)","Ridglea Country Club","Fort Worth","");
insert into tournament values(809611114,"SOUTHLAKE JUNIOR OPEN (Jr)","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(800038814,"The 13th Annual Marauder Spring Open (Non-Sanctioned)","TNT Tennis","Grapevine","");
insert into tournament values(809619414,"USTA National Opens","Waco Regional Tennis and Fitness","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(809643614,"Texoma Circuit 02-14 Wichita Falls (Jr, Ad, Sr, SS)","Weeks Park Tennis Center","Wichita Falls","weekspark@aol.com");
insert into tournament values(800025314,"8th Annual Rally For The Cure Tennis Open (Jr, Ad)","Walden On Lake Conroe","Montgomery","");
insert into tournament values(800020914,"Berry Creek Spring Open Benefiting Swing For Sobriety (Jr, Ad)","Berry Creek Racquet Club","Georgetown","");
insert into tournament values(800005314,"USTA National Men, Women & Mixed 30's Hard Court Championship","Westwood Country Club","Austin","");
insert into tournament values(800015814,"10s Participation Credit Tournament - Harlingen","Harlingen Junior Tennis Association","Harlingen","");
insert into tournament values(800038114,"Arlington Tennis Center Mid Cities Spring 2014 (Non-Sanctioned)","Arlington Tennis Center","Arlington","");
insert into tournament values(800006714,"Bay Area Racquet Club -Racquet Pro March Junior Open (Jr)","Bay Area Racquet Club","Houston","tennisref@century21.com");
insert into tournament values(800033714,"COPPERFIELD ZAT","Copperfield R. & H. Club","Houston","ref2go@aol.com");
insert into tournament values(809600514,"HIGH POINT ZAT","High Point Park Tennis Center","Plano","spulley12@hotmail.com");
insert into tournament values(800033414,"SATA ZAT","San Antonio Tennis Assn.","San Antonio","bthreadgill@stx.rr.com");
insert into tournament values(809674214,"SPRING BREAK SHOOTOUT JUNIOR CHAMPIONSHIP MAJOR ZONE (CMZ)","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(809634914,"Tournament Credit MAR 2014 (Adults/Seniors)","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(800033914,"BROOKHAVEN COUNTRY CLUB ADULT LEVELS (Ad)","Brookhaven Country Club","Dallas","rmtennis@yahoo.com");
insert into tournament values(800033114,"CATA Gran Prix Austin Tennis Academy Jr Open (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(800013814,"HOOTERS ADULT LEVELS OPEN (Non-Sanctioned)","Fair Oaks Ranch Country Club","Fair Oaks Ranch","");
insert into tournament values(809601514,"THE COURTYARD CLASSIC (Ad)","Courtyard Tennis Club","Austin","tdirector512@gmail.com");
insert into tournament values(800009814,"Abilene ZAT","Abilene Tennis Association","Abilene","allen.prachyl@abileneisd.org");
insert into tournament values(809643514,"BVTA 2014 Spring ZAT","BVTA - Organizer: Vicki Markowsky","Bryan","");
insert into tournament values(800045314,"Highland Village Mid Cities Spring 2014 (Non-Sanctioned)","Highland Village Tennis Center","Highland Village","");
insert into tournament values(800012914,"METROPLEX SPRING BREAK JUNIORS (Jr) Non-Qualified,Champs & Super Champs","Metroplex Tennis Association Inc.","Dallas","");
insert into tournament values(800017914,"MIDLAND CHAMPIONSHIP JUNIOR MAJOR ZONE (CMZ)","Tennis Association Of Midland","Midland","fsrainh2o@sbcglobal.net");
insert into tournament values(800018414,"Raveneaux & Champion Tennis Academy Jr Open (Jr)","Raveneaux Country Club","Spring","ginny_james@hotmail.com");
insert into tournament values(800030614,"Dallas OPEN: Non Qualified Jrs, Champ, Super, Adults, Seniors (Jr, Ad, Sr, SS)","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(809674114,"MCCTA March Tournament (Jr, Ad, Sr, SS)","Missouri City Cta","Missouri City","mccta123@comcast.net");
insert into tournament values(809641814,"2014 HTA HOUSTON SUPER CHAMP MAJOR ZONE (SCMZ 12_14)","Houston Tennis Association","Houston","");
insert into tournament values(800032414,"Brazos Valley Tennis Association Gran Prix 7-14 (Non-Sanctioned)","Brazos Valley Tennis Association","Bryan","");
insert into tournament values(800029314,"DPTA JUNIOR CIRCUIT No.7-HUFFHINES TC (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(809706114,"ECHOMETER SUPER CHAMP MAJOR ZONE (SCMZ 16_18)","Wichita Falls Tennis Association","Wichita Falls","weekspark@aol.com");
insert into tournament values(800011314,"March Madness Georgetown Junior Open (Jr)","Georgetown Tennis","Georgetown","mikemhenry@aol.com");
insert into tournament values(800034614,"TNT Tennis' Colleyville Spring Mid Cities (Non-Sanctioned)","TNT Tennis","Grapevine","");
insert into tournament values(800003914,"USTA National Men's 70 & 75 Indoor Championships","Downtown Club At The Met","Houston","ginny_james@hotmail.com");
insert into tournament values(800036914,"2014 Heaton Eye Hope Open Adult & Junior Open (Non-Sanctioned)","Tyler Tennis & Swim Club","Tyler","");
insert into tournament values(800042214,"2014 TAPPS Pre-District Tournament (Non-Sanctioned)","Regents School of Austin","Austin","");
insert into tournament values(800035214,"Canyon Creek Wilson Night (Non-Sanctioned)","Canyon Creek Country Club","Richardson","");
insert into tournament values(800033014,"CATA Gran Prix Cimarron Hills Jr Open (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(809703514,"Horseshoe Bay Resort Red Clay Junior Open (Jr)","Horseshoe Bay Resort","Horseshoe Bay","");
insert into tournament values(800015714,"LCCC WTA Spring Indoor Doubles Tournament (Ad)","Las Colinas Country Club","Irving","rmtennis@yahoo.com");
insert into tournament values(800041714,"TAPPS 4A Pre-District Tournament","San Marcos Academy","San Marcos","");
insert into tournament values(809666014,"TPI Hardcourt Classic (Jr, Ad, Sr, SS)","Tennis Professional International","Houston","aliciammorris@gmail.com");
insert into tournament values(800002014,"Waco Courtyard Marriott Adult and Junior Open (Jr, Ad, Sr, SS)","Waco Regional Tennis and Fitness","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(800006514,"2014 Little Mo Texas Sectionals (Non-Sanctioned)","Arlington Tennis Center","Arlington","");
insert into tournament values(800021214,"Aggieland Junior Open (Jr)","Aggieland Tennis","College Station","");
insert into tournament values(800026514,"Bay Oaks / Racquet Pro Spring Break Junior Open (Non-Sanctioned)","Bay Oaks Country Club","Houston","");
insert into tournament values(809603814,"DPTA ChampSuper Challenger Eldorado (Jr)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800027014,"Midcourt Cup #1 (Non-Sanctioned)","Samuell Grand Tennis Center","Dallas","");
insert into tournament values(800025414,"Odessa CC Future Stars Tournament (Jr)","Odessa Country Club","Odessa","");
insert into tournament values(800037614,"STC Spring Mid-Cities (Non-Sanctioned)","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(809660514,"ATA Spring Open and TennisRecruiting.net National Showcase (formerly Spenco Open) (Jr)","Austin Tennis Academy","Austin","mikemhenry@aol.com");
insert into tournament values(800030014,"BUCCANEER DAYS ADULT MAJOR ZONE (Ad, Sr)","Corpus Christi Tennis Association","Corpus Christi","terry@cctaonline.org");
insert into tournament values(800012314,"METROPLEX MARCH MADNESS ADULTS and JUNIORS Non-Qualified,Champs & Super Champs (Jr, Ad, Sr, SS)","Metroplex Tennis Association Inc.","Dallas","");
insert into tournament values(800008214,"Bay Area Racquet Club / Racquet Pro Junior Open (Jr)","Bay Area Racquet Club","Houston","tennisref@century21.com");
insert into tournament values(800039614,"DPTA Jr. Novice #1 Wagon Wheel (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800028514,"EDC Orange Competitive Training Camp (Non-Sanctioned)","Giammalva Racquet Club","Spring","ginny_james@hotmail.com");
insert into tournament values(800004214,"EDC Orange Competitive Training Camp (Non-Sanctioned)","Giammalva Racquet Club","Spring","ginny_james@hotmail.com");
insert into tournament values(800913814,"HOOTERS ADULT LEVELS OPEN (Non-Sanctioned)","Fair Oaks Ranch Country Club","Fair Oaks Ranch","");
insert into tournament values(800039214,"Richland Tennis Center Spring Mid Cities - 2014 (Non-Sanctioned)","Richland Tennis Center","North Richland Hills","");
insert into tournament values(800026414,"SOUTHLAKE FUTURE STARS #2 (Jr)","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(800003314,"USTA National Women's 35, 45, 55, 65, 75 & 85 Clay Court Championships","Houston Racquet Club","Houston","");
insert into tournament values(809612614,"Tournament Credit APR 2014 (Adults/Seniors)","Texas Tennis Foundation","Nixon","");
insert into tournament values(800039914,"2014 Little Mo Sectionals - Texas (Fair Oaks) (Non-Sanctioned)","Fair Oaks Ranch CC","Fair Oaks Ranch","");
insert into tournament values(800042314,"2014 TAPPS District Tournament (Non-Sanctioned)","Regents School of Austin","Austin","");
insert into tournament values(809691414,"Dallas Spring Open: Non Qualified Jrs, Champ, Super, Adults, Seniors (Jr, Ad, Sr, SS)","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(809602714,"First Serve Tennis Lone Star Levels Tournament (Ad)","Greater San Antonio Adult League Tennis","San Antonio","NogalitosGearSvc@aol.com");
insert into tournament values(800005714,"Giammalva RC Junior Open Tournament (Jr)","Giammalva Racquet Club","Spring","");
insert into tournament values(800015114,"Lakecliff Adult Open (Ad)","Lakecliff Raquet Club","Spicewood","edprice99@hotmail.com");
insert into tournament values(800025814,"Lost Creek Spring Junior Open (Jr)","Lost Creek Country Club","Austin","ncamillone@austin.rr.com");
insert into tournament values(800016814,"Roddick Series Fair Oaks Ranch Country Club  Jr Open (Jr)","Outreach Tennis Association, Inc.","San Antonio","");
insert into tournament values(800025514,"10's Participation Credit Tournament - Odessa","Odessa Country Club","Odessa","");
insert into tournament values(800043314,"10's Participation Credit Tournament - Wichita Falls","Wichita Falls Tennis Association","Wichita Falls","weekspark@aol.com");
insert into tournament values(800003814,"2014 Little Mo Sectionals - Florida (Daytona Beach)","Florida Tennis Center","Daytona Beach","");
insert into tournament values(800021314,"Aggieland Junior Open (Jr)","Aggieland Tennis","College Station","bgldbrg33@hotmail.com");
insert into tournament values(800037314,"DTA Spring ZAT","Dallas Tennis Assoc.","Addison","susan.wert10s@gmail.com");
insert into tournament values(800038014,"KATCH Mid-Cities (Non-Sanctioned)","Keller Alliance Tennis Charter","Keller","");
insert into tournament values(800024814,"Polo Tennis Club Future Stars (Jr)","Polo Tennis & Fitness Club","Austin","");
insert into tournament values(800022414,"TATA Spring Adult Tennis Challenge (Non-Sanctioned)","Taylor Area Tennis Association","Taylor","");
insert into tournament values(800022714,"Tennis Express/King Daddy Sports Champ Major Zone (CMZ)","King Daddy Sports","Houston","gdial1@comcast.net");
insert into tournament values(800003714,"Sr-Super Sr Major Zone Arlington Tennis Center (Sr, SS)","Arlington Tennis Center","Arlington","atc@arlingtontx.gov");
insert into tournament values(809658714,"GTC Adult Spring Slam (Ad)","Georgetown Tennis Center","Georgetown","mikemhenry@aol.com");
insert into tournament values(809708014,"MCCTA April Tournament (Jr, Ad, Sr, SS)","Missouri City Cta","Houston","miguelm2353@gmail.com");
insert into tournament values(800005914,"San Angelo Adult Major Zone (Ad)","SAPA","San Angelo","cnagel@bentwoodcc.com");
insert into tournament values(800035714,"Wilson Night (Non-Sanctioned)","Canyon Creek Country Club","Richardson","");
insert into tournament values(800001014,"2014 Little Mo Sectionals - Missouri Valley","Genesis Health Club","Wichita","");
insert into tournament values(800109814,"Abilene ZAT","Abilene Tennis Association","Abilene","allen.prachyl@abileneisd.org");
insert into tournament values(800038514,"Clear Lake Junior Open (Jr)","Clear Lake High School","Houston","");
insert into tournament values(800022614,"Crown Colony Heart Association Benefit","Crown Colony Country Club","Lufkin","");
insert into tournament values(800022814,"Crown Colony Heart Association Benefit (Non-Sanctioned)","Crown Colony Country Club","Lufkin","");
insert into tournament values(800039814,"DPTA Jr. Novice #2 Village (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(809642514,"Fort Stockton ZAT","Fort Stockton Tennis","Fort Stockton","fsrainh2o@sbcglobal.net");
insert into tournament values(809726714,"Hurst Junior Open (Jr)","Hurst Tennis Center","Hurst","susan.wert10s@gmail.com");
insert into tournament values(809623914,"KATY ZAT 2","Willow Fork Country Club","Katy","wfts@willowforktennisshop.com");
insert into tournament values(800010114,"Laredo Country Club Junior Open","Laredo Country Club","Laredo","");
insert into tournament values(800022314,"Laredo Country Club Junior Open","Laredo Country Club","Laredo","");
insert into tournament values(800022514,"Laredo Country Club Junior Open","Laredo Country Club","Laredo","");
insert into tournament values(809600614,"PLANO CHAMPIONSHIP MAJOR ZONE (CMZ)","High Point Park Tennis Center","Plano","");
insert into tournament values(800035314,"WACO TENNIS ASSN ZAT","Waco Tennis Association","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(800039314,"Walnut Creek Spring Mid Cities (Non-Sanctioned)","Walnut Creek Country Club","Mansfield","");
insert into tournament values(800001214,"UIL 5A Regional - Baylor University (Non-Sanctioned)","Kevin Foster / Hewitt Tennis Association","Hewitt","edprice99@hotmail.com");
insert into tournament values(800034514,"2014 HTA HOUSTON OPEN-ADULT MZ (Ad, Sr, SS)","Houston Tennis Association","Houston","htaharriett@houstontennis.org");
insert into tournament values(800005114,"Austin Super Championship Level 4 (SCMZ 12_14)","Capital Area Tennis Association","Austin","tjwright50@austin.rr.com");
insert into tournament values(800030714,"BROOKHAVEN COUNTRY CLUB ADULT LEVELS-SR OPEN (Ad, Sr, SS)","Brookhaven Country Club","Dallas","rmtennis@yahoo.com");
insert into tournament values(800011114,"WACO REGIONAL TENNIS CENTER SUPER CHAMP LEVEL 4  (SCMZ 16_18)","Waco Regional Tns Cntr","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(800004814,"DPTA Champ Super Challenger Fair Oaks (Jr)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800029514,"DPTA JUNIOR CIRCUIT No. 8 - LAKES TENNIS ACADEMY (Non-Sanctioned)","Dallas Professional Tennis Associatoni","Frisco","");
insert into tournament values(800012214,"Georgetown Easter Junior Open (Jr)","Georgetown Tennis","Georgetown","mikemhenry@aol.com");
insert into tournament values(800337014,"Midcourt Cup #2 (Non-Sanctioned)","Samuell Grand Tennis Center","Dallas","");
insert into tournament values(800034714,"TNT Tennis' Grapevine Spring Mid Cities (Non-Sanctioned)","TNT Tennis","Hurst","");
insert into tournament values(800003014,"2014 State TAPPS Tournament (Non-Sanctioned)","Hewitt Tennis Association","Hewitt","");
insert into tournament values(809680314,"THE COURTYARD CLASSIC Senior and Super Senior MZ (Sr, SS)","Courtyard Tennis Club","Austin","");
insert into tournament values(800035514,"Bring a Ringer Doubles Night (Non-Sanctioned)","Canyon Creek Country Club","Richardson","");
insert into tournament values(800040214,"2014 Little Mo Sectionals - Southern (Tennessee)","Tyson Family Tennis Center","Knoxville","");
insert into tournament values(800040314,"2014 Little Mo Sectionals - Texas (Kingwood) (Non-Sanctioned)","Kingwood Country Club","Kingwood","");
insert into tournament values(800007614,"3rd Annual Darren Lajaunie Memorial Adult & Junior Open (Non-Sanctioned)","Bay Area Racquet Club","Houston","");
insert into tournament values(800002114,"ALLEN SAMUELS Chrysler Dodge Jeep Ram  SUNBURST ADULT AND JUNIOR OPEN (Jr, Ad, Sr, SS)","Waco Regional Tns Cntr","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(800033214,"CATA Gran Prix Berry Creek Jr Open (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(800027514,"Jim Henry Tennis Open (Jr, Ad)","Bush Tennis Center","Midland","fsrainh2o@sbcglobal.net");
insert into tournament values(800013114,"METROPLEX ADULTS and JUNIORS Non-Qualified,Champs & Super Champs (Jr, Ad, Sr, SS)","Metroplex Tennis Association Inc.","Dallas","marvin.tp@verizon.net");
insert into tournament values(800017114,"Roddick Series Kingwood Country Club  Jr Open (Jr)","Outreach Tennis Association, Inc.","Kingwood","tmgatzki@yahoo.com");
insert into tournament values(800020014,"SAN ANTONIO FIESTA ADULT AND JUNIOR OPEN (Jr, Ad)","San Antonio Tennis Assn.","San Antonio","dnk57@sbcglobal.net");
insert into tournament values(800026214,"College Station Rotary Club Charity Classic/BVTA Gran Prix 8-13 (Non-Sanctioned)","Brazos Valley Tennis Association","Bryan","");
insert into tournament values(800066914,"Giammalva RC Future Stars (Jr)","Giammalva Racquet Club","Spring","");
insert into tournament values(800029014,"SOUTHLAKE FUTURE STARS #3 (Jr)","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(800035014,"Thomas J Henry Junior Open (Jr)","H E B Municipal Tennis Center","Corpus Christi","terry.sweet@att.net");
insert into tournament values(800039714,"Wagon Wheel Tennis Center Mid Cities (Non-Sanctioned)","Wagon Wheel Tennis Center","Coppell","");
insert into tournament values(809612914,"Tournament Credit MAY 2014 (Adults/Seniors)","Texas Tennis Foundation","Austin","");
insert into tournament values(800024914,"AESA Jr Open at Polo Tennis Club (Jr)","Polo Tennis & Fitness Club","Austin","mikemhenry@aol.com");
insert into tournament values(800015314,"Lakecliff Adult Open (Ad)","Lakecliff Raquet Club","Spicewood","");
insert into tournament values(809674614,"MCCTA May Tournament (Jr, Ad, Sr, SS)","Missouri City Cta","Sugar Land","mccta123@comcast.net");
insert into tournament values(800020614,"NRH Adult Open (Ad, Sr, SS)","Richland Tennis Center","North Richland Hills","");
insert into tournament values(800042614,"USTA Texas Section Invitational Match Play Camp (Non-Sanctioned)","MPC held at: Lost Creek Country Club","Austin","");
insert into tournament values(800035814,"Wilson Night (Non-Sanctioned)","Canyon Creek Country Club","Richardson","");
insert into tournament values(800029414,"10's Participation Credit Tournament - Amarillo","Amarillo Area Tennis Association","Amarillo","");
insert into tournament values(800040414,"2014 Little Mo Sectionals - Middle States","Aronimink Tennis Center","Newton Square","");
insert into tournament values(800035614,"AMARILLO CHAMPIONSHIP MAJOR ZONE (CMZ)","Amarillo Area Tennis Association","Amarillo","john@dataflow.us");
insert into tournament values(800050314,"Denton Mid Cities Spring 2014 (Non-Sanctioned)","Goldfield Tennis Center City of Denton","Denton","");
insert into tournament values(800029714,"DPTA JUNIOR CIRCUIT No. 9 - ELDORADO COUNTRY CLUB (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800011614,"Oasis Non-Qualified/Champ/Super Spring Junior Open (Jr)","Oasis Beach and Tennis Club","Rockwall","");
insert into tournament values(809601014,"RACQUET PRO DEER PARK SPRING ZAT","Deer Park Tennis","Deer Park","patnjohn65@aol.com");
insert into tournament values(809661014,"Tyler Spring ZAT","Faulkner Tennis Center","Tyler","davidkemp.dk@gmail.com");
insert into tournament values(800042914,"2014 NJCAA D1 Women's Tennis National Championships (Non-Sanctioned)","Tyler Junior College","Tyler","");
insert into tournament values(800042814,"SOS Tennis Benefit 23rd Annual Charity Event (Non-Sanctioned)","Southlake Tennis Center","Southlake","");
insert into tournament values(800040514,"2014 Little Mo Sectionals - Northern","LifeTime Fitness","Fridley","");
insert into tournament values(809620714,"COPPERFIELD RACQUET CLUB ADULT LEVELS OPEN (Ad)","Copperfield Racquet & Health Club","Houston","dlab46@aol.com");
insert into tournament values(809600914,"DALLAS CLASSIC: Non Qualified Jrs, Champ, Super, Adults, Seniors (Jr, Ad, Sr, SS)","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(800005814,"Polo Tennis Club Spring Adult NTRP Open (Ad)","Polo Tennis & Fitness Club","Austin","edgarperrey@aol.com");
insert into tournament values(809666314,"TPI Open Junior Classic (Jr)","Tennis Professional International","Houston","mrsaliciathomas@gmail.com");
insert into tournament values(800021514,"Aggieland Junior Open (Jr)","Aggieland Tennis","College Station","bgldbrg33@hotmail.com");
insert into tournament values(809701314,"CCTA MAY CHAMPS MAJOR ZONE (CMZ)","Corpus Christi Tennis Association","Corpus Christi","terry@cctaonline.org");
insert into tournament values(800039414,"Lifetime Fitness Mid-Cities Tournament 2014 (Non-Sanctioned)","Life Time Fitness-Colleyville","Colleyville","");
insert into tournament values(800010514,"Lost Creek ZAT","Lost Creek Country Club","Austin","camillone@gmail.com");
insert into tournament values(800009114,"Walnut Creek Spring ZAT","Walnut Creek Country Club","Mansfield","");
insert into tournament values(809621014,"WICHITA FALLS ZAT","Wichita Falls Tennis Association","Wichita Falls","");
insert into tournament values(800031514,"2014 NJCAA Division I Men's National Tennis Championship (Non-Sanctioned)","Collin County Community College","Plano","");
insert into tournament values(800331514,"2014 NJCAA Division III Men's National Tennis Championship (Non-Sanctioned)","Collin County Community College","Plano","");
insert into tournament values(809684014,"Texas Open Wheelchair Championships (Jr, Ad, Sr)","Dallas Wheelchair Tennis Club","Highland Village","susan.wert10s@gmail.com");
insert into tournament values(800035914,"Bring a Ringer Doubles Night (Non-Sanctioned)","Canyon Creek Country Club","Richardson","");
insert into tournament values(800033314,"CATA Gran Prix Onion Creek Jr Open (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(809705914,"Dallas Pre-Major Zone Warm-up (Non Qualified Jrs, Champs, Ad, Sr, SS)","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(800013014,"Horseshoe Bay Resort Red Clay Spring Open (Ad)","Horseshoe Bay Resort","Horseshoe Bay","");
insert into tournament values(800030514,"2014 HTA HOUSTON SUPER CHAMP LEVEL 4  (SCMZ 16_18)","Houston Tennis Association","Houston","");
insert into tournament values(800016414,"CATA 10 & Under Grey Rock Tennis Club  (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(800036114,"DALLAS TENNIS ASSOCIATION SUPER CHAMPIONSHIP LEVEL 4 (SCMZ 12_14)","Dallas Tennis Association","Addison","susan.wert10s@gmail.com");
insert into tournament values(800028014,"DPTA Jr. Novice #3 Jack Coleman (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800004014,"Giammalva RC Junior Open Tournament (Jr)","Giammalva Racquet Club","Spring","");
insert into tournament values(800043514,"Golfcrest Tennis Association Blast Into Summer (Non-Sanctioned)","Golfcrest Country Club","Pearland","");
insert into tournament values(800026314,"His Helping Hands Adult and Junior Open (Non-Sanctioned)","Faulkner Tennis Center","Tyler","");
insert into tournament values(800042014,"Peloton Ridge Future Stars (Jr)","PRCC TENNIS","Harker Heights","harrison_foster@ymail.com");
insert into tournament values(800017214,"Roddick Series Kerrville Jr Open (Jr)","Outreach Tennis Association, Inc.","Kerrville","director@austintennis.org");
insert into tournament values(800038914,"TNT Tennis' Grapevine Spring Open (Non-Sanctioned)","TNT Tennis","Grapevine","");
insert into tournament values(800038714,"Trophy Club Country Club Spring 2014 Mid Cities (Non-Sanctioned)","Trophy Club Country Club","Trophy Club","");
insert into tournament values(800024114,"Woodlands Centre Court Adult Open (Ad, Sr, SS)","Woodlands Tennis","Spring","bgldbrg33@hotmail.com");
insert into tournament values(800036514,"Westwood Senior Championships (Sr, SS)","Westwood Country Club","Austin","");
insert into tournament values(800040714,"2014 Little Mo Sectionals - Northern California","University of The Pacific","Stockton","");
insert into tournament values(809660714,"ATA Pre Summer Grand Slam Open (formerly Spenco Open) (Jr)","Austin Tennis Academy","Austin","spulley12@hotmail.com");
insert into tournament values(800008414,"Bay Area Racquet Club Fajitas & Ritas Adult & Junior Open (Jr, Ad)","Bay Area Racquet Club","Houston","tennisref@century21.com");
insert into tournament values(800030814,"Bub Walthall Memorial Day Adult and Junior Open (Jr, Ad)","San Antonio Tennis Assn.","San Antonio","bthreadgill@stx.rr.com");
insert into tournament values(800020314,"CHARLIE MC CLEARY WACO OPEN-ADULT AND JUNIOR OPEN (Jr, Ad, Sr, SS)","Waco Tennis Association","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(800027214,"KTSU Tennis Classic (Non-Sanctioned)","KTSU Tennis Tournament Committee","Houston","");
insert into tournament values(800019414,"WALNUT CREEK JUNIOR OPEN (Jr)","Walnut Creek Country Club","Mansfield","");
insert into tournament values(800040814,"2014 Little Mo Sectionals - Mid-Atlantic (Maryland)","Montgomery TennisPlex","Boyds","");
insert into tournament values(800041014,"2014 Little Mo Sectionals - Midwest","Homewood-Flossmoor Racquet Club","Homewood","");
insert into tournament values(800040914,"2014 Little Mo Sectionals - New England (Massachusetts)","Longfellow Club","Wayland","");
insert into tournament values(809662314,"48th Annual Lake Conroe Open (Jr)","Walden On Lake Conroe","Montgomery","gdial1@comcast.net");
insert into tournament values(800042414,"Brazos Valley Tennis Association Gran Prix 9-14 (Non-Sanctioned)","Brazos Valley Tennis Association","Bryan","");
insert into tournament values(800027814,"DPTA JUNIOR CIRCUIT No. 10 - HUFFHINES TC (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800039014,"Hackberry Creek Spring Mid Cities (Non-Sanctioned)","Hackberry Creek Country Club","Irving","");
insert into tournament values(800043114,"Missouri City Doubles Tournament (Non-Sanctioned)","Missouri City Recreation and Tennis Cent","Missouri City","");
insert into tournament values(800044214,"Texoma Circuit 05-14 (Jr, Ad, Sr, SS)","Weeks Park Tennis Center","Wichita Falls","weekspark@aol.com");
insert into tournament values(800001414,"USTA National Selection Tournament","Deer Park I.S.D./Deer Park Tennis","Deer Park","patnjohn65@aol.com");
insert into tournament values(800040114,"USTA National Selection Tournament-May","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(800041114,"2014 Little Mo Sectionals - Eastern","Armonk Tennis Club","Armonk","");
insert into tournament values(800025714,"32nd ANNUAL RICHARDSON OPEN (Jr, Ad, Sr, SS)","Huffhines Tennis Center","Richardson","lonestarpictures@aol.com");
insert into tournament values(800033514,"CATA Gran Prix River Place Jr Open (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(809709814,"JCC Junior Open (Jr)","Barshop Jewish Community Center","San Antonio","");
insert into tournament values(800043614,"Bay Oaks May Open (Non-Sanctioned)","Bay Oaks Country Club","Houston","");
insert into tournament values(800023114,"Centre Court Grand Slam Warmup Jr. Open (Jr)","Woodlands Tennis","Spring","bgldbrg33@hotmail.com");
insert into tournament values(800024314,"Doubles ONLY Champ Major Zone - Austin (CMZ)","Austin Tennis Academy","Austin","");
insert into tournament values(800009014,"DOUBLES ONLY CHAMP MAJOR ZONE - Southlake (CMZ)","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(800027914,"DPTA JUNIIOR CIRCUIT No. 11 - FAIR OAKS TC (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800012414,"Grand Slam Warmup Georgetown Junior Open (Jr)","Georgetown Tennis","Georgetown","mikemhenry@aol.com");
insert into tournament values(800043214,"Midcourt Cup #3 (Non-Sanctioned)","Samuell Grand Tennis Center","Dallas","");
insert into tournament values(800026614,"PRCC Roland Garros Celebration Open (Non-Sanctioned)","PRCC TENNIS","Harker Heights","");
insert into tournament values(800018114,"Roddick Series Harlingen Jr Open (Jr)","Outreach Tennis Association, Inc.","Harlingen","");
insert into tournament values(800034814,"TNT Tennis' Hurst Spring Mid Cities (Non-Sanctioned)","TNT Tennis","Hurst","");
insert into tournament values(809613014,"Tournament Credit JUN 2014 (Adults/Seniors)","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(800034014,"CATA Gran Prix Grey Rock Jr Grand Slam (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(800025914,"Lost Creek Adult Classic (Ad)","Lost Creek Country Club","Austin","camillone@gmail.com");
insert into tournament values(809674514,"MCCTA June Tournament (Jr, Ad, Sr, SS)","Missouri City Cta","Houston","mccta123@comcast.net");
insert into tournament values(800010314,"PLANO OPEN (Ad)","High Point Park Tennis Center","Plano","spulley12@hotmail.com");
insert into tournament values(800026814,"10's Participation Credit Tournament - Lubbock","South Plains Tennis Association","Lubbock","");
insert into tournament values(800041214,"2014 Little Mo Sectionals - New England (Vermont)","Topnotch Resort","Stowe","");
insert into tournament values(800037814,"AMARILLO ZAT","Amarillo Area Tennis Association","Amarillo","john@dataflow.us");
insert into tournament values(800037214,"BCS Schools Out 2014 ZAT","BVTA - Organizer: Vicki Markowsky","Bryan","");
insert into tournament values(800032114,"CORPUS CHRISTI ZAT","Corpus Christi Tennis Association","Corpus Christi","terry@cctaonline.org");
insert into tournament values(800011814,"Fair Oaks Junior Open (Jr)","Fair Oaks Tennis Center","Dallas","Lonestarpictures@aol.com");
insert into tournament values(800040614,"Hackberry Creek Summer Mid-Cities (Non-Sanctioned)","Hackberry Creek Country Club","Irving","");
insert into tournament values(800037714,"LUBBOCK HWY 80 CHAMP JUNIOR MAJOR ZONE (CMZ)","South Plains Tennis Association","Lubbock","tedge12@valornet.com");
insert into tournament values(800034914,"SATA CHAMPIONSHIP MAJOR ZONE (CMZ)","San Antonio Tennis Assn.","San Antonio","");
insert into tournament values(800055014,"SOUTHLAKE ZAT","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(800045714,"USTA Texas JTT Spring Season - Tournament Credit","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(809711814,"TWILIGHT TENNIS - GRAND SLAM WARM UP (Jr, Ad, Sr, SS)","Metroplex Tennis Association Inc.","McKinney","");
insert into tournament values(800042114,"$$ Tennis Ball Open $$","Bush Tennis Center","Midland","");
insert into tournament values(800041414,"2014 Little Mo Sectionals - Florida (Port St. Lucie)","Club Med Sandpiper","Port St. Lucie","");
insert into tournament values(800041314,"2014 Little Mo Sectionals - Pacific Northwest","Sprinker Tennis Center","Tacoma","");
insert into tournament values(800006614,"Capsher Texas Grand Slam (SCMZ 12_18)","BCS Grand Slam","Bryan","");
insert into tournament values(809661114,"East Texas Adult Major Zone (Ad)","Tyler Junior College","Tyler","");
insert into tournament values(800017314,"Roddick Series Marble Falls Junior and Adult Open (Jr, Ad)","Outreach Tennis Association, Inc.","Horseshoe Bay (Tournament in Marble Falls, TX)","director@austintennis.org");
insert into tournament values(809728214,"The Championship Masters at the Capsher Texas Grand Slam (CMZ Masters)","BCS Grand Slam","Bryan","");
insert into tournament values(800045214,"Walnut Creek Summer Mid Cities (Non-Sanctioned)","Walnut Creek Country Club","Mansfield","");
insert into tournament values(800041514,"2014 Little Mo Sectionals - Mid-Atlantic (Virginia Beach)","Virginia Beach & Tennis Club","Virginia Beach","");
insert into tournament values(800041614,"2014 Little Mo Sectionals - Southern California","Barnes Tennis Center","San Diego","");
insert into tournament values(800043914,"2014 7th Annual Mixed & Doubles Championships (Non-Sanctioned)","City of Edinburg","Edinburg","");
insert into tournament values(800033614,"DPTA Jr Novice # 4 Canyon Creek (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800004114,"Giammalva RC Junior Open Tournament (Jr)","Giammalva Racquet Club","Spring","");
insert into tournament values(800019314,"Kerrville Summer ZAT","H.E.B. Municipal Tennis Center","Kerrville","");
insert into tournament values(800020714,"NRH Junior Open (Jr)","Richland Tennis Center","N Richlnd Hls","");
insert into tournament values(800023214,"Sports Express Adult Open (Ad)","The Woodlands Tennis","Spring","gdial1@comcast.net");
insert into tournament values(800036014,"Bring a Ringer Doubles Night (Non-Sanctioned)","Canyon Creek Country Club","Richardson","");
insert into tournament values(800043714,"2014 Edinburg Summer Tennis Classic (Non-Sanctioned)","City of Edinburg","Edinburg","");
insert into tournament values(800025014,"AESA Jr Open at Polo Tennis Club (Jr)","Polo Tennis & Fitness Club","Austin","");
insert into tournament values(800044414,"Bayard H Friedman Summer Mid-Cities (Non-Sanctioned)","Bayard H. Friedman Tennis Center","Fort Worth","");
insert into tournament values(800007814,"Chancellors INDOORS Summer Series Adult Open (Ad)","Bay Area Racquet Club","Houston","");
insert into tournament values(800043014,"Laredo Country Club Adult Open (Ad)","Laredo Country Club","Laredo","");
insert into tournament values(800013214,"METROPLEX SUMMER CLASSIC ADULTS and JUNIORS Non-Qualified,Champs & Super Champs (Jr, Ad, Sr, SS)","Metroplex Tennis Association Inc.","Dallas","");
insert into tournament values(800001114,"WOODLANDS JUNIOR CLAY COURT CHAMPIONSHIPS (Jr)","The Woodlands Cnty. Club","The Woodlands","ref2go@aol.com");
insert into tournament values(800007114,"BARC Racquet Pro Future Stars #2 Tournament (Jr)","Bay Area Racquet Club","Houston","");
insert into tournament values(800042514,"Brazos Valley Tennis Association Gran Prix 10-14 (Non-Sanctioned)","Brazos Valley Tennis Association","Bryan","");
insert into tournament values(800028814,"DPTA JUNIOR CIRCUIT No. 12 - COOPER FITNESS CENTER (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800945314,"Highland Village Mid Cities Summer 2014 (Non-Sanctioned)","Highland Village Tennis Center","Highland Village","");
insert into tournament values(800002514,"Odessa Country Club Hwy 80 (Jr)","Odessa Country Club","Odessa","fsrainh2o@sbcglobal.net");
insert into tournament values(800030114,"SOUTHLAKE FUTURE STARS #4 (Jr)","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(809713514,"USONP - Sectional Qualifying (Texas)","Arlington Tennis Center","Arlington","susan.wert10s@gmail.com");
insert into tournament values(809608714,"Al Edwards JUNETEENTH Tennis Classic (Ad, Sr, SS)","Juneteenth USA","Houston","tennisref@century21.com");
insert into tournament values(800034114,"CATA Gran Prix Lost Creek Jr Open (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(800017714,"McAllen Open (Non-Sanctioned)","City of McAllen Park and Rec.","McAllen","");
insert into tournament values(800006414,"Oasis June Adult Open (Ad)","Oasis Beach and Tennis Club","Rockwall","spulley12@hotmail.com");
insert into tournament values(800044814,"River Crest Summer Mid-Cities Jr. Tournament (Non-Sanctioned)","River Crest Country Club","Fort Worth","");
insert into tournament values(809667214,"TPI Texas Open (Jr)","Tennis Professional International","Houston","mrsaliciathomas@gmail.com");
insert into tournament values(800048514,"Aggieland Junior Open (Jr)","Aggieland Tennis","College Station","bgldbrg33@hotmail.com");
insert into tournament values(809660114,"Arlington Tennis Association Junior Singles Open (Jr)","Arlington Tennis Association","Arlington","");
insert into tournament values(800027614,"Corpus Christi CC Junior Open (Jr)","Corpus Christi Country Club","Corpus Christi","gerry@cctennisshop.com");
insert into tournament values(800029914,"DPTA JUNIOR CIRCUIT No. 13 - FAIR OAKS (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800043814,"Grace Prep Tennis Classic (Non-Sanctioned)","Walnut Creek Country Club","Mansfield","");
insert into tournament values(809728614,"Kerrville Junior Summer Classic (Jr)","H.E.B. Municipal Tennis Center","Kerrville","");
insert into tournament values(800017814,"Roddick Series Beaumont Jr. and Adult Open (Jr, Ad)","Outreach Tennis Assn, Inc./Beaumont Tennis Center","Beaumont","director@austintennis.org");
insert into tournament values(800006314,"SAN ANGELO HIGHWAY 80 (Jr)","SAPA","San Angelo","cnagel@bentwoodcc.com");
insert into tournament values(800094014,"TNT Tennis' Colleyville Summer Mid Cities (Non-Sanctioned)","TNT Tennis","Grapevine","");
insert into tournament values(809613114,"Tournament Credit JUL 2014 (Adults/Seniors)","Texas Tennis Foundation","Nixon","");
insert into tournament values(809633614,"USTA Texas Registration Site - USTA B&G 12 Zone Team Championships","USTA Texas Section","Omaha","");
insert into tournament values(809634014,"USTA Texas Registration Site-USTA B&G 14 Zone Team Championships","USTA Texas Section","Arlington","");
insert into tournament values(809634114,"USTA Texas Registration Site-USTA B&G 16 Zone Team Championships","USTA Texas Section","Waco","");
insert into tournament values(800000914,"USTA Zone Team Championship- BG14","Arlington Parks & Recreation","Arlington","atc@arlingtontx.gov");
insert into tournament values(800000314,"USTA Zone Team Championships","St. Stephen's Episcopal School","Austin","director@austintennis.org");
insert into tournament values(800001614,"USTA Zone Team Championships- BG16","Waco Regional Tennis and Fitness","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(809799814,"LCCC WTA Mid Year Indoor Doubles Tournament (Ad)","Las Colinas Country Club","Irving","rmtennis@yahoo.com");
insert into tournament values(809719914,"MCCTA JULY OPEN (Jr, Ad, Sr, SS)","Missouri City Cta","Missouri City","mccta123@comcast.net");
insert into tournament values(800010714,"HOUSTON TENNIS ASSOCIATION CHAMPIONSHIP MAJOR ZONE (CMZ)","Houston Tennis Association","Houston","");
insert into tournament values(800012514,"Independence Day Georgetown Junior Open (Jr)","Georgetown Tennis","Georgetown","mikemhenry@aol.com");
insert into tournament values(809638514,"LUBBOCK Summer ZAT","South Plains Tennis Association","Lubbock","tedge12@valornet.com");
insert into tournament values(800026714,"PRCC Wimbledon Celebration Championships (Non-Sanctioned)","PRCC TENNIS","Harker Heights","");
insert into tournament values(800016014,"The Courts at McKinney Junior Open (Jr)","The Courts at Gabe Nesbitt Park","McKinney","");
insert into tournament values(800023314,"The Woodlands July Jr Open (Jr)","Woodlands Tennis","Spring","bgldbrg33@hotmail.com");
insert into tournament values(809611514,"Grey Rock Tennis Club Adult NTRP Tournament (Ad)","Grey Rock Tennis Club","Austin","tennis512@gmail.com");
insert into tournament values(800041814,"2014 Little Mo Sectionals - Florida (Sarasota)","Serendipity","Sarasota","");
insert into tournament values(800010814,"Bending Branch Winery Adult Major Zone (Ad, Sr, SS)","San Antonio Tennis Assn.","San Antonio","RPerme2002@yahoo.com");
insert into tournament values(800021714,"DALLAS SUMMER OPEN and PRIZE MONEY DOUBLES: Non Qualified Jrs, Champs & Supers (Jr, Ad, Sr, SS)","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(800045114,"Richland Tennis Center Summer Mid Cities - 2014 (Non-Sanctioned)","Richland Tennis Center","North Richland Hills","");
insert into tournament values(800022114,"Aggieland Junior Open (Jr)","Aggieland Tennis","College Station","bgldbrg33@hotmail.com");
insert into tournament values(800003614,"Arlington Tennis Center ZAT","Arlington Parks & Recreation","Arlington","");
insert into tournament values(800007214,"Bay Area Racquet Club -Racquet Pro July Junior Open (Jr)","Bay Area Racquet Club","Houston","");
insert into tournament values(800027714,"Bush Tennis Center Future Stars (Jr)","Midland Tennis Center","Midland","");
insert into tournament values(809661314,"Ellen Waters Memorial Championship Junior Major Zone (CMZ)","Faulkner Tennis Center","Tyler","davidkemp.dk@gmail.com");
insert into tournament values(800004614,"Marti Rodriguez Memorial - Austin ZAT","Capital Area Tennis Association","Austin","tjwright50@austin.rr.com");
insert into tournament values(800010614,"RACQUET PRO PASADENA ZAT","Strawberry Tennis Center","Pasadena","coachdunivan@aol.com");
insert into tournament values(800044514,"Ridglea Country Club Summer Mid-Cities Jr Tournament (Non-Sanctioned)","Ridglea Country Club","Fort Worth","");
insert into tournament values(800010414,"WACO REGIONAL TENNIS CENTER ZAT","Waco Regional Tns Cntr","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(800045414,"TWILIGHT TENNIS CELEBRATION (Jr, Ad, Sr, SS)","Metroplex Tennis Association Inc.","McKinney","");
insert into tournament values(800045614,"9th Annual - Joe Best Memorial Tennis Tournament (Non-Sanctioned)","South Texas CTA","McAllen","");
insert into tournament values(800034214,"CATA Gran Prix Barton Creek Jr Grand Slam (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(800024214,"FORT WORTH ADULT MAJOR ZONE (Ad)","Fort Worth Tennis Association","Fort Worth","susan.wert10s@gmail.com");
insert into tournament values(800036614,"Horseshoe Bay Resort Red Clay Championship (Ad)","Horseshoe Bay Resort","Horseshoe Bay","");
insert into tournament values(800340814,"TNT Tennis' Hurst Summer Mid Cities (Non-Sanctioned)","TNT Tennis","Hurst","");
insert into tournament values(800030314,"10's Participation Credit Tournament - Corpus Christi","Corpus Christi Tennis Association","Corpus Christi","terry@cctaonline.org");
insert into tournament values(800009914,"Abilene Super Championship Major Zone (SCMZ 12_14)","Abilene Tennis Association","Abilene","allen.prachyl@abileneisd.org");
insert into tournament values(800010214,"ALAMO CITY SUPER CHAMPIONSHIP MAJOR ZONE (SCMZ 16_18)","San Antonio Tennis Assn.","San Antonio","rmoench@satx.rr.com");
insert into tournament values(800038214,"DEER PARK JUNIOR OPEN (Jr)","Deer Park Tennis","Deer Park","patnjohn65@aol.com");
insert into tournament values(800030414,"DPTA JUNIOR CIRCUIT No. 14 - T BAR M (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800016314,"Fair Oaks (Dallas) Fall Classic (Jr)","Fair Oaks Tennis Center","Dallas","Lonestarpictures@aol.com");
insert into tournament values(800029614,"SOUTHLAKE FUTURE STARS #5 (Jr)","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(800019514,"WALNUT CREEK JUNIOR SHOOTOUT (Jr)","Walnut Creek Country Club","Mansfield","");
insert into tournament values(809697014,"USTA Zone Team Championships- BG16","Waco Regional Tennis and Fitness","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(800045014,"2014 Texas A&M ITA Summer Circuit (Non-Sanctioned)","Texas A. & M. Tennis","College Station","");
insert into tournament values(800005514,"Beary Sun-Brrrrr....'nd 'nothing but doubles' (Ad)","Capital Area Tennis Association","Austin","tjwright50@austin.rr.com");
insert into tournament values(800033814,"CATA Gran Prix Hyatt Lost Pines Jr Grand Slam at ATC (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(800007914,"Chancellors INDOORS Summer Series #2 Adult & Junior Open (Jr, Ad)","Bay Area Racquet Club","Houston","");
insert into tournament values(809710214,"Fair Oaks (Dallas) Summer Open (Ad, Sr, SS)","Fair Oaks Tennis Center","Dallas","Lonestarpictures@aol.com");
insert into tournament values(809703714,"Horseshoe Bay Resort Red Clay Classic Junior Open (Jr)","Horseshoe Bay Resort","Horseshoe Bay","");
insert into tournament values(800018014,"Roddick Series Fair Oaks Ranch Country Club  Jr Open (Jr)","Outreach Tennis Association, Inc.","San Antonio","");
insert into tournament values(800036214,"Wilson Night","Canyon Creek Country Club","Richardson","");
insert into tournament values(809604114,"DPTA ChampSuper Challenger Lakes Tennis Academy (Jr)","Dallas Professional Tennis Association","Dallas","lonestarpictures@aol.com");
insert into tournament values(800028114,"DPTA Jr Novice # 5 Oasis Beach and Tennis (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800031014,"DPTA JUNIOR CIRCUIT No. 15 - HACKBERRY CC (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800048014,"KATCH Mid-Cities (Non-Sanctioned)","Keller Alliance Tennis Charter","Keller","");
insert into tournament values(800044114,"KATCH Mid-Cities Tournament","Keller Alliance Tennis Charter","Keller","");
insert into tournament values(800018514,"Raveneaux Junior Singles Championship (Jr)","Raveneaux Country Club","Spring","ginny_james@hotmail.com");
insert into tournament values(800003214,"USTA National Warm Up Tournament","Giammalva Racquet Club","Spring","");
insert into tournament values(800023414,"Woodlands Adult Open (Ad)","The Woodlands Tennis","Spring","bgldbrg33@hotmail.com");
insert into tournament values(800000614,"USTA National Warm Up Tournament- Boys 14","Austin Tennis Academy","Austin","RPerme2002@yahoo.com");
insert into tournament values(800016714,"BROOKHAVEN COUNTRY CLUB ADULT LEVELS (Ad)","Brookhaven Country Club","Dallas","rmtennis@yahoo.com");
insert into tournament values(800008914,"TLU Bulldog Junior Open (Jr)","Texas Lutheran University","Seguin","herberttennis@cpu-net.net");
insert into tournament values(800347014,"TNT Tennis' Grapevine Summer Mid Cities (Non-Sanctioned)","TNT Tennis","Hurst","");
insert into tournament values(809613214,"Tournament Credit AUG 2014 (Adults/Seniors)","Texas Tennis Foundation","Austin","");
insert into tournament values(809641214,"Amarillo ZAT","Amarillo Area Tennis Association","Amarillo","john@dataflow.us");
insert into tournament values(800044314,"Arlington Tennis Center Mid Cities Summer 2014 (Non-Sanctioned)","Arlington Tennis Center","Arlington","");
insert into tournament values(800012714,"BERRY CREEK ZAT","Berry Creek Racquet Club","Georgetown","");
insert into tournament values(800028214,"DPTA Jr Novice # 6 Northwood CC (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800031214,"DPTA JUNIOR CIRCUIT No. 16 - COOPER FITNESS CENTER (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800013314,"METROPLEX JUNIOR CHAMPIONSHIP (Jr) Non-Qualified,Champs & Super Champs","Metroplex Tennis Association Inc.","Dallas","");
insert into tournament values(800023514,"Summer Slam Junior Open (Jr)","Woodlands Tennis","Spring","bgldbrg33@hotmail.com");
insert into tournament values(800024414,"TAAF Summer Games of Texas (Non-Sanctioned)","City of College Station Park & Rec Dept","College Station","");
insert into tournament values(800000714,"USTA National Championship-  Boys' 14","San Antonio Tennis Association","San Antonio","ginny_james@hotmail.com");
insert into tournament values(800024614,"CATA Gran Prix Lakeway Jr Grand Slam (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(800034314,"CATA Gran Prix Lakeway WOT Jr Grand Slam (Non-Sanctioned)","Capital Area Tennis Association","Austin","director@austintennis.org");
insert into tournament values(809639414,"COPPERFIELD JUNIOR OPEN (Jr)","Copperfield Racquet & Health Club","Houston","dlab46@aol.com");
insert into tournament values(800044914,"Las Colinas Summer Mid Cities (Non-Sanctioned)","Las Colinas Country Club","Irving","");
insert into tournament values(800019614,"WALNUT CREEK SUMMER SIZZLER (Ad)","Walnut Creek Country Club","Mansfield","ncebersole@yahoo.com");
insert into tournament values(809689414,"2014 Harlingen ZAT","Harlingen Junior Tennis Association","Harlingen","");
insert into tournament values(800010914,"Abilene Champ Major Zone (CMZ)","Abilene Tennis Association","Abilene","allen.prachyl@abileneisd.org");
insert into tournament values(809634214,"Arlington Tennis Center Super Championship Major Zone (SCMZ 16_18)","Arlington Tennis Center","Arlington","");
insert into tournament values(800012814,"BCS Back to School 2014 ZAT","BVTA - Organizer: Vicki Markowsky","Bryan","");
insert into tournament values(809661214,"Bob Faulkner Super Championship Junior Major Zone (SCMZ 12_14)","Faulkner Tennis Center","Tyler","davidkemp.dk@gmail.com");
insert into tournament values(800016514,"Canyon Creek ZAT","Canyon Creek Country Club","Richardson","");
insert into tournament values(800023614,"Head / Penn Adult Open (Ad)","woodlands tennis","Spring","bgldbrg33@hotmail.com");
insert into tournament values(800045514,"STC SUMMER MID-CITIES (Non-Sanctioned)","Southlake Tennis Center","Southlake","");
insert into tournament values(800044714,"2nd Annual Summer Scorcher Adult Open at Ridglea Country Club (Doubles Only)(Non-Sanctioned)","Ridglea Country Club","Fort Worth","");
insert into tournament values(800011914,"Fair Oaks (Dallas) Summer Classic (Ad, Sr, SS)","Fair Oaks Tennis Center","Dallas","Lonestarpictures@aol.com");
insert into tournament values(800013914,"FAIR OAKS RANCH JUNIOR OPEN (San Antonio) (Jr)","Fair Oaks Ranch Country Club","Fair Oaks Ranch","");
insert into tournament values(800026014,"Lost Creek Summer Junior Open (Jr)","Lost Creek Country Club","Austin","camillone@gmail.com");
insert into tournament values(809674914,"MCCTA August Tournament (Jr, Ad, Sr, SS)","Missouri City Cta","Missouri City","mccta123@comcast.net");
insert into tournament values(800036314,"Wilson Night","Canyon Creek Cc","Richardson","");
insert into tournament values(800950314,"Denton Mid Cities Summer 2014 (Non-Sanctioned)","Goldfield Tennis Center City of Denton","Denton","");
insert into tournament values(800025614,"Katy Champ Major Zone (CMZ)","Willow Fork Country Club","Katy","");
insert into tournament values(809605414,"SOUTHLAKE JUNIOR OPEN (Jr)","Southlake Tennis Center","Southlake","");
insert into tournament values(809660614,"ATA Summer Open (formerly Spenco Open) (Jr)","Austin Tennis Academy","Austin","RPerme2002@yahoo.com");
insert into tournament values(800008114,"Chancellors INDOORS Summer Series #3 Adult & Junior Open (Jr, Ad)","Bay Area Racquet Club","Houston","");
insert into tournament values(809703814,"Horseshoe Bay Resort Red Clay Summer Classic (Ad)","Horseshoe Bay Resort","Horseshoe Bay","");
insert into tournament values(800008614,"Oasis Summer Sizzler Adult Open (Ad)","Oasis Beach and Tennis Club","Rockwall","spulley12@hotmail.com");
insert into tournament values(809604014,"DPTA ChampSuper Challenger Village Tennis Center (Jr)","Dallas Professional Tennis Association","Dallas","lonestarpictures@aol.com");
insert into tournament values(800028314,"DPTA Jr Novice # 7 Las Colinas (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800004314,"Giammalva RC Junior Open Tournament (Jr)","Giammalva Racquet Club","Spring","");
insert into tournament values(800044614,"SOUTHLAKE FUTURE STARS #6 (Jr)","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(800019014,"95th ANNUAL BEAUMONT LABOR DAY TENNIS CLASSIC (Jr, Ad)","Beaumont Labor Day Tennis Org","Bridge City","");
insert into tournament values(800011414,"CHOCbite.com Labor Day Open (Ad)","Capital Area Tennis Assn","Austin","tjwright50@austin.rr.com");
insert into tournament values(800015414,"Lakecliff Junior Open (Jr)","Lakecliff Raquet Club","Spicewood","");
insert into tournament values(800021414,"Tea Cup Open (Jr, Ad, Sr, SS)","Tennis Professional International","HOUSTON","aliciammorris@gmail.com");
insert into tournament values(800022214,"Aggieland Junior Open (Jr)","Aggieland Tennis","College Station","bgldbrg33@hotmail.com");
insert into tournament values(800004914,"Austin Tennis Academy Spenco Super Champ Level 4 (SCMZ 12_14)","Austin Tennis Academy","Austin","RPerme2002@yahoo.com");
insert into tournament values(800009214,"Canyon Creek Super Championship Level 4 (SCMZ 16_18)","Canyon Creek Country Club","Richardson","");
insert into tournament values(800031314,"DPTA JUNIOR CIRCUIT MASTERS  - HUFFHINES TC (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(809659614,"SOUTHLAKE FALL CELEBRATION (Ad)","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(809613314,"Tournament Credit SEP 2014 (Adults/Seniors)","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(809620814,"2014 Copperfield Cup sponsored by The Loken Group (Ad)","Copperfield Racquet & Health Club","Houston","dlab46@aol.com");
insert into tournament values(800020114,"Clear Lake Champ Major Zone (CMZ)","Clear Lake High School","Houston","");
insert into tournament values(800014114,"DALLAS ZAT","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(809604214,"DPTA ChampSuper Challenger Garland (Jr)","Dallas Professional Tennis Association","Dallas","lonesstapictures@aol.com");
insert into tournament values(809678114,"HOTT ZAT","BBI Tennis Group","Belton","herberttennis@cpu-net.net");
insert into tournament values(809660314,"HTA NJTL ZAT","Houston Tennis Association","Houston","");
insert into tournament values(800014314,"LUBBOCK FALL ZAT","South Plains Tennis Association","Lubbock","tedge12@valornet.com");
insert into tournament values(800008314,"Oasis Champ/Super Fall Junior Open (Jr)","Oasis Beach and Tennis Club","Rockwall","");
insert into tournament values(800036414,"Bring a Ringer Doubles Night","Canyon Creek Country Club","Richardson","");
insert into tournament values(800017014,"CHARLIE WEAVER TEXAS ADULT SECTIONALS (Ad)","San Antonio Tennis Assn.","San Antonio","RPerme2002@yahoo.com");
insert into tournament values(809691714,"Dallas Champ Super & Non-Qualified Juniors, Adults and Seniors (Jr, Ad, Sr, SS)","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(809667414,"TPI JUNIOR TENNIS CLASSIC (Jr)","Tennis Professional International","Houston","mrsaliciathomas@gmail.com");
insert into tournament values(800024514,"Arlington Tennis Center Champ Major Zone (CMZ)","Arlington Parks & Recreation","Arlington","");
insert into tournament values(800017614,"Corpus Christi Fall ZAT","Corpus Christi Tennis Association","Corpus Christi","terry@cctaonline.org");
insert into tournament values(800012614,"Georgetown Fall Kickoff Junior Open (Jr)","Georgetown Tennis","Georgetown","mikemhenry@aol.com");
insert into tournament values(800042714,"The GrapeFest Tennis Classic (Junior)","TNT Tennis","Grapevine","");
insert into tournament values(800009514,"T Bar M Racquet Club INDOOR Senior & Super Senior MZ (Sr, SS)","T. Bar M. Racquet Club","Dallas","Lonestarpictures@aol.com");
insert into tournament values(800048614,"Berry Creek Open (Ad, Sr)","Berry Creek Racquet Club","Georgetown","");
insert into tournament values(809703914,"Horseshoe Bay Resort Red Clay Fall Open (Jr)","Horseshoe Bay Resort","Horseshoe Bay","");
insert into tournament values(800009414,"Hurst Adult Open (Ad)","Hurst Tennis Center","Hurst","susan.wert10s@gmail.com");
insert into tournament values(809675014,"MCCTA September Tournament (Jr, Ad, Sr, SS)","Missouri City Cta","Missouri City","mccta123@comcast.net");
insert into tournament values(800013714,"Polo Tennis Club Fall Adult NTRP Open (Ad)","Polo Tennis & Fitness Club","Austin","");
insert into tournament values(800036714,"Wilson Night","Canyon Creek Country Club","Richardson","");
insert into tournament values(800027314,"Giammalva RC Future Stars (Jr)","Giammalva Racquet Club","Spring","");
insert into tournament values(800016614,"GII Junior Open (Jr)","Gloger Interests, Inc","Houston","");
insert into tournament values(800027114,"GII Junior Open (Jr)","Gloger Interests, Inc","Houston","");
insert into tournament values(800013414,"METROPLEX JUNIOR CLASSIC (Jr) Non-Qualified, Champs & Super Champs","Metroplex Tennis Association Inc.","Dallas","");
insert into tournament values(809660914,"ATA Fall Open and TennisRecruiting.net National Showcase (formerly Spenco Open) (Jr)","Austin Tennis Academy","Austin","RPerme2002@yahoo.com");
insert into tournament values(800017514,"BROOKHAVEN COUNTRY CLUB ADULT LEVELS (Ad)","Brookhaven Country Club","Dallas","rmtennis@yahoo.com");
insert into tournament values(809658614,"GTC Adult Fall Championships (Ad)","Georgetown Tennis Center","Georgetown","mikemhenry@aol.com");
insert into tournament values(800016114,"King Daddy Sports September Junior Open (Jr)","King Daddy Sports","Houston","");
insert into tournament values(800040014,"Patrick Wayne Fagan Tennis Classic (Ad, Sr, SS)","Tennis Professional International","Missouri City","mrsaliciathomas@gmail.com");
insert into tournament values(800016914,"CHILDREN HELPING CHILDREN JUNIOR SINGLES (Jr)","High Point Park Tennis Center","Plano","");
insert into tournament values(800028414,"DPTA Jr. Novice Circuit #8 Stonebridge Ranch CC (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800030214,"SOUTHLAKE FUTURE STARS #7 (Jr)","Southlake Tennis Center","Southlake","susan.wert10s@gmail.com");
insert into tournament values(809613414,"Tournament Credit OCT 2014 (Adults/Seniors)","Texas Tennis Foundation","Nixon","");
insert into tournament values(809644614,"2014 Houston Fall Festival SUPER SENIOR MZ (SS)","Houston Tennis Association","Houston","");
insert into tournament values(800017414,"2014 HOUSTON FALL FESTIVAL Senior MZ and Adult Open (Ad, Sr)","Houston Tennis Association","Houston","");
insert into tournament values(800025114,"AESA Jr Open at Polo Tennis Club (Jr)","Polo Tennis & Fitness Club","Austin","");
insert into tournament values(800015514,"Lakecliff Fall Open (Ad)","Lakecliff Raquet Club","Spicewood","");
insert into tournament values(800020514,"TEXAS STATE FAIR CLASSIC: Champs, Supers, Adults (Jr, Ad, Sr, SS)","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(800006914,"BVTA October Champ Major Zone 2014 (CMZ)","BVTA - Organizer: Vicki Markowsky","Bryan","");
insert into tournament values(800014014,"Corpus Christi Future Stars (Jr)","Corpus Christi Tennis Association","Corpus Christi","terry@cctaonline.org");
insert into tournament values(809644114,"Frisco ZAT","Lakes Tennis Academy","Frisco","Lonestarpictures@aol.com");
insert into tournament values(800014414,"MCFARLIN ZAT","San Antonio Tennis Assn.","San Antonio","woerner@gvtc.com");
insert into tournament values(800014214,"RACQUET PRO DEER PARK FALL ZAT","Deer Park Tennis","Deer Park","patnjohn65@aol.com");
insert into tournament values(800006114,"SAN ANGELO ZAT","SAPA","San Angelo","cnagel@bentwoodcc.com");
insert into tournament values(800023714,"Woodlands  Fall Jr Open (Jr)","Woodlands Tennis","Spring","bgldbrg33@hotmail.com");
insert into tournament values(809662214,"48th Annual Lake Conroe Open (Ad, Sr, SS)","Walden On Lake Conroe","Montgomery","gdial1@comcast.net");
insert into tournament values(800011014,"Abilene Adult Open (Adult 200pt tournament) (Ad)","Abilene Tennis Association","Abilene","allen.prachyl@abileneisd.org");
insert into tournament values(800008514,"Courtyard Compass Doubles (Ad)","Courtyard Tennis Club","Austin","director@austintennis.org");
insert into tournament values(800009714,"Oasis Fall Adult Open (Ad)","Oasis Beach and Tennis Club","Rockwall","spulley12@hotmail.com");
insert into tournament values(800037014,"Wilson Night","Canyon Creek Country Club","Richardson","");
insert into tournament values(800039613,"Closed USTA Regional Tournament - National Level 4 Ranking","South Plains Tennis Association","Lubbock","susan.wert10s@gmail.com");
insert into tournament values(800000214,"Laredo Tennis Association Champ Major Zone (CMZ)","Laredo Tennis Association","Laredo","rccavazos@cs.com");
insert into tournament values(800007014,"The Courts at McKinney Junior Open (Jr)","The Courts at Gabe Nesbitt Park","McKinney","");
insert into tournament values(800003114,"USTA National Selection Tournament","Giammalva Racquet Club","Spring","");
insert into tournament values(800000514,"USTA National Selection Tournament- October","St. Stephen's Episcopal School","Austin","director@austintennis.org");
insert into tournament values(800002314,"USTA National Selection Tournament- October","Tennis Association Of Midland","Midland","fsrainh2o@sbcglobal.net");
insert into tournament values(800014514,"WACO TENNIS ASSOC ZAT #2","Waco Tennis Association","Waco","");
insert into tournament values(809675114,"MCCTA October Tournament (Jr, Ad, Sr, SS)","Missouri City Cta","Missouri City","mccta123@comcast.net");
insert into tournament values(800013514,"METROPLEX FALL CLASSIC ADULTS and JUNIORS Non-Qualified,Champs & Super Champs (Jr, Ad, Sr, SS)","Metroplex Tennis Association Inc.","Dallas","");
insert into tournament values(800028614,"DPTA Jr. Novice Circuit #9 Prestonwood CC (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800018914,"ECHOMETER SUPER CHAMP EXCELLENCE (SCMZ 12_16)","Wichita Falls Tennis Association","Wichita Falls","weekspark@aol.com");
insert into tournament values(800027414,"Giammalva RC Future Stars (Jr)","Giammalva Racquet Club","Spring","");
insert into tournament values(809642114,"SATA Super Champ Excellence (SCMZ 14_18)","San Antonio Tennis Association","San Antonio","drbeck3055@gmail.com");
insert into tournament values(800018214,"World of Tennis Category II Championship (SS)","Lakeway Wrld Of Tns CC","Austin","tennis512@gmail.com");
insert into tournament values(809659014,"GTC Halloween Junior Open (Jr)","Georgetown Tennis Center","Georgetown","camillone@gmail.com");
insert into tournament values(800037114,"Halloween Spooktacular Doubles Night","Canyon Creek Country Club","Richardson","");
insert into tournament values(800046314,"Horseshoe Bay Resort Howlin' Open (Ad)","Horseshoe Bay Resort","Horseshoe Bay","");
insert into tournament values(800020214,"WACO REGIONAL TENNIS CENTER-GOBLINS ADULTS & JUNIOR OPEN (Jr, Ad, Sr)","Waco Regional Tns Cntr","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(809604514,"DPTA ChampSuper Challenger T-Bar-M (Jr)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800022014,"Hill Country Future Stars (Jr)","H.E.B. Municipal Tennis Center","Kerrville","");
insert into tournament values(809687214,"Houston Junior Fall Festival (Jr)","Houston Tennis Association","Houston","");
insert into tournament values(800018314,"Roddick Series Corpus Christi Jr Open (Jr)","Outreach Tennis Association, Inc.","Corpus Christi","");
insert into tournament values(800007314,"SOUTHLAKE FUTURE STARS #8 (Jr)","Southlake Tennis Center","Southlake","");
insert into tournament values(809660214,"Arlington Tennis Association ZAT","Arlington Tennis Association","Arlington","");
insert into tournament values(800028714,"DPTA Jr. Novice #10 Bent Tree (Non-Sanctioned)","Dallas Professional Tennis Association","Dallas","");
insert into tournament values(800012014,"Fair Oaks (Dallas) Fall Classic (Jr)","Fair Oaks Tennis Center","Dallas","Lonestarpictures@aol.com");
insert into tournament values(809681614,"King Daddy Sports November Junior Open (Jr)","King Daddy Sports","Houston","");
insert into tournament values(800018614,"PLANO FALL CHAMPIONSHIP MAJOR ZONE (CMZ)","High Point Park Tennis Center","Plano","");
insert into tournament values(800006214,"San Angelo ZAT","SAPA","San Angelo","cnagel@bentwoodcc.com");
insert into tournament values(800014714,"SATA SOUTHWEST ZAT","San Antonio Tennis Assn.","San Antonio","woerner@gvtc.com");
insert into tournament values(809613514,"Tournament Credit NOV 2014 (Adults/Seniors)","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(800009614,"Oasis Senior/Super Senior Major Zone (Sr, SS)","Oasis Beach and Tennis Club","Rockwall","Lonestarpictures@aol.com");
insert into tournament values(800005614,"2014 USTA National MD, Sr. MD, & Super Sr. MD  Hard Court Championships","Walden On Lake Conroe","Montgomery","gtrouble452@yahoo.com");
insert into tournament values(800019714,"BOB NOEL TENNIS CLASSIC (Ad)","Walnut Creek Country Club","Mansfield","ncebersole@yahoo.com");
insert into tournament values(800037414,"Wilson Night","Canyon Creek Country Club","Richardson","");
insert into tournament values(800003514,"BCS Super Champ Level 4 (SCMZ 16_18)","BVTA - Organizer: Daniel Marshall","Bryan","");
insert into tournament values(800026114,"Denton ZAT","City of Denton - Goldfield Tennis Center","Denton","Lonestarpictures@aol.com");
insert into tournament values(800029214,"Polo Tennis Club Future Stars (Jr)","Polo Tennis & Fitness Club","Austin","");
insert into tournament values(800018814,"RACQUET PRO PASADENA CHAMPIONSHIP JUNIOR MAJOR ZONE (CMZ)","Strawberry Tennis Center","Pasadena","coachdunivan@aol.com");
insert into tournament values(800014814,"SOUTHEAST TEXAS TENNIS ASSOCIATION ZAT","Lamar University","Beaumont","");
insert into tournament values(809642214,"Waco Regional Tennis Center Super Champ Level 4 (SCMZ 12_14)","Waco Regional Tennis and Fitness","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(800023814,"Woodlands Thanksgiving Adult Open (Ad, Sr)","The Woodlands High School","The Woodlands","bgldbrg33@hotmail.com");
insert into tournament values(809703214,"2014 USTA National Women's Intersectional Team Event","Texas Tennis & Education Foundation","Austin (TOURNAMENT-San Antonio)","");
insert into tournament values(809679914,"ATA Holiday Open (formerly Spenco Open) (Jr)","Austin Tennis Academy","Austin","RPerme2002@yahoo.com");
insert into tournament values(809691614,"Dallas Fall: Non Qualified Jrs, Champ, Super, & Adults (Jr, Ad, Sr, SS)","Steve Franklin Tennis Services","Dallas","Lonestarpictures@aol.com");
insert into tournament values(809675314,"MCCTA November Tournament (Jr, Ad, Sr, SS)","Missouri City Cta","Sugar Land","mccta123@comcast.net");
insert into tournament values(800004714,"Pok-e-Jo's Simply the BEST - 2014 Texas Adult Masters Championships (Ad)","Capital Area Tennis Association","Austin","");
insert into tournament values(809652114,"64th ANNUAL THANKSGIVING OPEN FOR JUNIORS AND ADULTS (Jr, Ad, Sr)","Corpus Christi Tennis Association","Corpus Christi","terry@cctaonline.org");
insert into tournament values(800021814,"Hill Country Turkey Open (Jr, Ad, Sr, SS)","H.E.B. Municipal Tennis Center","Kerrville","");
insert into tournament values(800000114,"Laredo Tennis Association Adult Open Tournament (Ad)","Laredo Tennis Association","Laredo","rccavazos@cs.com");
insert into tournament values(800002214,"METROPLEX ADULT CHAMPIONSHIP (Ad, Sr, SS)","Metroplex Tennis Association Inc.","Dallas","");
insert into tournament values(809691914,"TPI BRIGHTWATER OPEN (Jr, Ad, Sr, SS)","Tennis Professional International","Houston","mrsaliciathomas@gmail.com");
insert into tournament values(800037914,"56th LeMaster Husband & Wife Tournament (Non-Sanctioned)","Houston Tennis Association","Houston","");
insert into tournament values(800004414,"Arlington Tennis Center Champ MZ Doubles (CMZ)","Arlington Tennis Center","Arlington","");
insert into tournament values(800004514,"Giammalva RC Doubles ONLY Champ Major Zone (CMZ)","Giammalva Racquet Club","Spring","");
insert into tournament values(800011714,"Turkey Shoot Georgetown Junior Open (Jr)","Georgetown Tennis","Georgetown","mikemhenry@aol.com");
insert into tournament values(800037514,"Turkey Tune-up Junior Singles Tournament","Canyon Creek Country Club","Richardson","");
insert into tournament values(809682814,"Break-It-Out 2014 ChampSuper (Jr)","Garland Tennis Association","Garland","");
insert into tournament values(809719614,"Open USTA Regional Tournament - Level 2","Austin Tennis Academy","Austin","RPerme2002@yahoo.com");
insert into tournament values(800001814,"Open USTA Regional Tournament Segment- November (Waco)","Waco Regional Tennis and Fitness","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(800001514,"USTA National Selection Touranment- November","Waco Regional Tennis and Fitness","Waco","evelynjane1020@hot.rr.com");
insert into tournament values(809719314,"USTA National Selection Tournament","Austin Tennis Academy","Austin","RPerme2002@yahoo.com");
insert into tournament values(800002614,"USTA National Selection Tournament","Waco Regional Tennis and Fitness","Waco","");
insert into tournament values(800002714,"USTA National Selection Tournament- November","Steve Franklin Tennis Services","Grand Prairie","Lonestarpictures@aol.com");
insert into tournament values(800002914,"USTA National Selection Tournament- November","Giammalva Racquet Club","Spring","");
insert into tournament values(800007414,"Bay Area Racquet Club November Jr Tournament (Jr)","Bay Area Racquet Club","Houston","");
insert into tournament values(800029814,"Break-It-Out 2014 Beginning & ZAT Level (Non-Sanctioned)","Garland Tennis Association","Garland","");
insert into tournament values(809613614,"Tournament Credit DEC 2014 (Adults/Seniors)","Texas Tennis & Education Foundation","Austin","");
insert into tournament values(800055814,"HARRY TAYLOR PASADENA ADULT OPEN (Ad)","Strawberry Tennis Center","Pasadena","");
insert into tournament values(809703614,"Horseshoe Bay Resort Red Clay Holiday Open (Ad)","Horseshoe Bay Resort","Horseshoe Bay","");
insert into tournament values(809722914,"LCCC  WTA Farewell Year Indoor Doubles Tournament (Ad)","Las Colinas Country Club","Irving","");
insert into tournament values(800018714,"SOUTH TEXAS ADULT & JUNIOR OPEN (Jr, Ad)","San Antonio Tennis Assn.","San Antonio","woerner@gvtc.com");
insert into tournament values(800005214,"Austin Junior Championship Major Zone (CMZ)","Capital Area Tennis Association","Austin","tjwright50@austin.rr.com");
insert into tournament values(809723714,"BVTA Super Champ Major Zone (SCMZ 12_14)","BVTA - Organizer: Vicki Markowsky","Bryan","");
insert into tournament values(800095914,"COTTON BOWL SUPER CHAMPIONSHIP MAJOR ZONE (SCMZ 16_18)","Dallas Tennis Assoc.","Addison","susan.wert10s@gmail.net");
insert into tournament values(800015014,"HTA ZAT #2","Houston  Tennis Assoc.","Houston","");
insert into tournament values(800009314,"Laredo ZAT","Laredo Tennis Association","Laredo","rccavazos@cs.com");
insert into tournament values(809640514,"Midland December ZAT","Tennis Association Of Midland","Midland","fsrainh2o@sbcglobal.net");
insert into tournament values(800019214,"Oasis Holiday Junior Open (Jr)","Oasis Beach and Tennis Club","Rockwall","");
insert into tournament values(800023914,"Sports Express Christmas Woodlands  Jr Open (Jr)","The Woodlands High School","The Woodlands","bgldbrg33@hotmail.com");
insert into tournament values(809675414,"MCCTA December Tournament (Jr, Ad, Sr, SS)","Missouri City Cta","Sugar Land","mccta123@comcast.net");
insert into tournament values(800011514,"Oasis Holiday Adult Open (Ad)","Oasis Beach and Tennis Club","Rockwall","spulley12@hotmail.com");
insert into tournament values(800011214,"Abilene Champ Major Zone (CMZ)","Abilene Tennis Association","Abilene","allen.prachyl@abileneisd.org");
insert into tournament values(809603114,"DPTA ChampSuper Challenger Lakes (Jr)","Dallas Professional Tennis Association","Dallas","Lonestarpictures@aol.com");
insert into tournament values(800015214,"HIGH POINT FALL ZAT","High Point Park Tennis Center","Plano","");
insert into tournament values(800008814,"Newk's ZAT","John Newcombe's Tennis Ranch","New Braunfels","");
insert into tournament values(800013614,"METROPLEX HOLIDAY CLASSIC ADULTS and JUNIORS Non-Qualified,Champs & Super Champs (Jr, Ad, Sr, SS)","Metroplex Tennis Association Inc.","Dallas","");
insert into tournament values(800007514,"Bay Area Racquet Club Holiday Junior Open (Jr)","Bay Area Racquet Club","Houston","tennisref@century21.com");
insert into tournament values(800024014,"Christmas Woodlands Adult Open (Ad, Sr)","The Woodlands High School","The Woodlands","bgldbrg33@hotmail.com");
insert into tournament values(800019814,"COTTON BOWL CLASSIC - Adult Major Zone & Junior Open (Jr, Ad, Sr)","Dallas Tennis Assoc.","Addison","susan.wert10s@gmail.net");
insert into tournament values(809664214,"TPI Orange Bowl (Jr)","Tennis Professional International","Houston","mrsaliciathomas@gmail.com");
